// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDHIVO_sypMTcJYCMfKBJv8b_rt6vYlik',
    appId: '1:256652788791:web:1436de22b6e0efe6c1ebb2',
    messagingSenderId: '256652788791',
    projectId: 'photo-diary-e45c1',
    authDomain: 'photo-diary-e45c1.firebaseapp.com',
    storageBucket: 'photo-diary-e45c1.appspot.com',
    measurementId: 'G-09T8T8NSS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF_T_YDN4r0qm-nHaDlHzYo9w6vVkcmKU',
    appId: '1:256652788791:android:2a3dd31df6a0a564c1ebb2',
    messagingSenderId: '256652788791',
    projectId: 'photo-diary-e45c1',
    storageBucket: 'photo-diary-e45c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByS37R2rh-9K7ZwOa4aloL5GHA-FAFjFQ',
    appId: '1:256652788791:ios:0d325490fe26a08fc1ebb2',
    messagingSenderId: '256652788791',
    projectId: 'photo-diary-e45c1',
    storageBucket: 'photo-diary-e45c1.appspot.com',
    iosClientId: '256652788791-hoh17plti1fo9gt3g0s5drki662k8dig.apps.googleusercontent.com',
    iosBundleId: 'com.example.photodiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByS37R2rh-9K7ZwOa4aloL5GHA-FAFjFQ',
    appId: '1:256652788791:ios:29a0aaa94006865bc1ebb2',
    messagingSenderId: '256652788791',
    projectId: 'photo-diary-e45c1',
    storageBucket: 'photo-diary-e45c1.appspot.com',
    iosClientId: '256652788791-sds788tf6qies128jvaqnbs8li7c7rgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.photodiary.RunnerTests',
  );
}
